FROM --platform=linux/amd64 ubuntu:latest

RUN apt-get update -qq && \
    apt-get install -y -qq \
    gcc nasm make mtools dosfstools gnu-efi \
    >/dev/null 2>&1 && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /src
